name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  access-token:
    description: 'LINE Access Token'
    required: true
  repository-name:
    description: 'Repository name'
    required: true
  issue-number:
    description: 'Issue No.'
    required: true
  issue-title:
    description: 'Issue Title'
    required: true
  issue-html-url:
    description: 'Issue Title'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'